### ISSUE TITLE
python eval.py 报错 AssertionError: e

### ISSUE THREAD

**Issue by WkangLiu** [lartpang/PySODEvalToolkit#17]
python check_path.py

/home/lkw/PySODEvalToolkit/examples/config_method_json_example.json & /home/lkw/PySODEvalToolkit/examples/config_dataset_json_example.json 基本正常

python eval.py (省略参数)
Traceback (most recent call last):
  File "/data1/lkw/PySODEvalToolkit/eval.py", line 168, in <module>
    main()
  File "/data1/lkw/PySODEvalToolkit/eval.py", line 137, in main
    datasets_info = get_datasets_info(
  File "/data1/lkw/PySODEvalToolkit/utils/generate_info.py", line 156, in get_datasets_info
    targeted_datasets = get_valid_elements(
  File "/data1/lkw/PySODEvalToolkit/utils/generate_info.py", line 61, in get_valid_elements
    assert element in source, element
AssertionError: e

请问这是怎么了？

**Comment by WkangLiu** [comment]
还有一个不确定的地方，我在设置json文件时
GT和method GT都是.png文件，但是我在设置后缀时是这么表示的
**dataset**
`    "mask": {
      "path": "/home/lkw/BGNet/data/TestDataset/CAMO/GT",
      "prefix": "",
      "suffix": ".png"
`

method****
`    "CAMO": {
      "path": "/home/lkw/BGNet/results/BGNet_tran31_2/37/CAMO/GT",
      "prefix": "",
      "suffix": ".png"
`

我不太明确这么弄对不对，因为按照说明我认为我的后缀时相同的，我可以用“”代替，但是这么会报错
