### ISSUE TITLE
import py_sod_metrics ??

### ISSUE THREAD

**Issue by fa3ima95** [lartpang/PySODEvalToolkit#22]
hello.
could not find the file of py_sod_metrics. does it upload?

Traceback (most recent call last):
  File "/content/drive/MyDrive/camouflaged/project1/s1/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/PySODEvalToolkit/./eval.py", line 7, in <module>
    from metrics import cal_sod_matrics
  File "/content/drive/MyDrive/camouflaged/project1/s1/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/PySODEvalToolkit/metrics/cal_sod_matrics.py", line 14, in <module>
    from utils.recorders import (
  File "/content/drive/MyDrive/camouflaged/project1/s1/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/PySODEvalToolkit/utils/recorders/__init__.py", line 4, in <module>
    from .metric_recorder import (
  File "/content/drive/MyDrive/camouflaged/project1/s1/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/PySODEvalToolkit/utils/recorders/metric_recorder.py", line 50, in <module>
    "handler": py_sod_metrics.FmeasureHandler,
AttributeError: module 'py_sod_metrics' has no attribute 'FmeasureHandler'
trained

**Comment by wmnj** [comment]
hello, Could you tell me how to address this problem? Thank you very much.

**Comment by lartpang** [comment]
@wmnj

Do you install the metric library `pysodmetrics`?
 https://github.com/lartpang/PySODEvalToolkit/blob/a8ae171b0f0bb10a368b7cb88e5ceb78b2403486/requirements.txt#L42
