### ISSUE TITLE
运行eval_all.py文件报错

### ISSUE THREAD

**Issue by Wickyan** [lartpang/PySODEvalToolkit#6]
您好我遇到了以下问题
```
C:\Users\wickyan\.conda\envs\torch\python.exe F:/PySODEvalToolkit/examples/eval_all.py
`../output`已存在
Traceback (most recent call last):
  File "F:/PySODEvalToolkit/examples/eval_all.py", line 70, in <module>
    use_mp=False,  # using multi-threading
  File "F:\PySODEvalToolkit\metrics\cal_sod_matrics.py", line 113, in cal_sod_matrics
    max_method_name_width=max([len(x) for x in drawing_info.keys()]),  # 显示完整名字
ValueError: max() arg is an empty sequence

进程已结束，退出代码为 1
```
将max_method_name_width设置成固定值8，又会造成output文件夹中输出为“空”：
```
 ========>> Date: 2021-11-18 01:01:04.917841 <<======== 

 ========>> Dataset: LFSD <<======== 

 ========>> Dataset: NLPR <<======== 

 ========>> Date: 2021-11-18 01:43:13.467784 <<======== 

 ========>> Dataset: LFSD <<======== 

 ========>> Dataset: NLPR <<======== 
```
）使用check_path.py检查路径显示：基本正常
请教出现了什么问题，谢谢

**Comment by lartpang** [comment]
从你的信息中可以看到，你的drawing_info.keys()是空的，也就是先需要检查一下drawing_info的信息是否正常。

**Comment by lartpang** [comment]
由于核心代码最近更新了一些内容，导致仓库里的eval_all的脚本可能有些旧了？我先尽快更新下examples中的例子，并进一步补充使用说明。

**Comment by Wickyan** [comment]
感谢，使用了https://github.com/lartpang/PySODEvalToolkit/commit/897612b6975f3de2e5003e35703972b41c47ebfc
最新版本之后，能够正常运行了，好耶！
